version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # production SPA (unchanged)
#  frontend:
#    build: ./site
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend
#    restart: unless-stopped

  # NEW: hot‑reloading dev server
  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm install --foreground-scripts && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./site:/app          # live mount source code
      - /app/node_modules    # keep deps inside container
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
