name: infra-plan-drift

on:
  push:
    paths:
      - 'infra/terraform/**'
      - 'infra/s3-bucket-diagnostics/**'

jobs:
  drift-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infra/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-1
      AWS_REGION: us-west-1
      TF_IN_AUTOMATION: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Ensure AWS CLI v2
        run: |
          if ! command -v aws >/dev/null 2>&1; then
            curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
            unzip -q awscliv2.zip
            sudo ./aws/install
          fi
          aws --version

      - name: Terraform init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform plan (detailed exit code)
        id: plan
        run: |
          set +e
          terraform plan -detailed-exitcode -no-color -out plan.tfplan
          exit_code=$?
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
          terraform show -no-color plan.tfplan > plan-full.txt
          grep -E "^Plan:" -m1 plan-full.txt > plan.txt || echo "Plan summary unavailable" > plan.txt
          exit 0

      - name: Upload plan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-drift
          path: |
            infra/terraform/plan.txt
            infra/terraform/plan-full.txt
            infra/terraform/plan.tfplan
          if-no-files-found: error

      - name: Fail on drift
        if: steps.plan.outputs.exit_code == '2'
        run: |
          echo "Terraform reported changes. See artifacts for details."
          exit 1
